"""
Quiz queue service.

Manages item ordering and selection strategy for each user session.
The route calls queue.next_item(items) instead of random.choice() -- the queue
handles all mode logic internally, so the route stays thin.

Queue state is cached by session_id (a UUID generated by the frontend on first load).
Items are never stored in the queue -- it holds only indices and weights, pointing
into the item list that already lives in the subject cache.

Supported modes:
  random     -- pure random, no state, items can repeat immediately
  shuffle    -- no repeats until deck exhausted, then reshuffle
  sequential -- in order, wraps at end
  mini-batch -- N items at a time, then next batch, reshuffle when deck exhausted
  weighted   -- miss more = see more, uses random.choices() with per-item weights
"""

import random

from backend.core.cache import CacheProvider, InMemoryCache
from backend.core.config import DEFAULT_BATCH_SIZE, DEFAULT_QUEUE_MODE
from backend.models.quiz import QuizItem


class QuizQueue:
    """
    Stateful item selector for a quiz session.

    Holds lightweight state (indices, weights, position) that points into
    an externally-owned item list. The item list is passed in on each call
    to next_item() so the queue never duplicates subject data.
    """

    def __init__(self, mode: str = DEFAULT_QUEUE_MODE, batch_size: int = DEFAULT_BATCH_SIZE) -> None:
        self.mode = mode
        self.batch_size = batch_size
        self._indices: list[int] = []
        self._batch_remaining: list[int] = []
        self._position: int = 0
        # Weights keyed by characters string. Only populated in weighted mode.
        self._weights: dict[str, float] = {}

    # ---------------------------------------------------------------------------
    # Public interface
    # ---------------------------------------------------------------------------

    def next_item(self, items: list[QuizItem]) -> QuizItem:
        """
        Return the next item based on the current mode.

        Args:
            items: The full item list from the subject cache.

        Returns:
            The selected QuizItem.
        """
        if not items:
            raise ValueError("Cannot select from an empty item list.")

        if self.mode == "random":
            return random.choice(items)
        elif self.mode == "shuffle":
            return self._next_shuffle(items)
        elif self.mode == "sequential":
            return self._next_sequential(items)
        elif self.mode == "mini-batch":
            return self._next_mini_batch(items)
        elif self.mode == "weighted":
            return self._next_weighted(items)
        else:
            return random.choice(items)

    def record_result(self, characters: str, correct: bool) -> None:
        """
        Adjust the weight for an item based on the guess result.

        Only active in weighted mode -- no-op for all other modes.
        Weights are capped between 1.0 (normal) and 3.0 (seen 3x more often).

        Args:
            characters: The compound that was shown.
            correct: Whether the user's guess was correct.
        """
        if self.mode != "weighted":
            return
        current = self._weights.get(characters, 1.0)
        if correct:
            self._weights[characters] = max(1.0, current - 0.5)
        else:
            self._weights[characters] = min(3.0, current + 1.0)

    def configure(self, mode: str, batch_size: int) -> None:
        """
        Change the queue mode and batch size, resetting all state.

        Resets on every configure call so the new mode starts clean
        regardless of what the previous mode was doing.

        Args:
            mode: One of 'random', 'shuffle', 'sequential', 'mini-batch', 'weighted'.
            batch_size: Number of items per mini-batch (used in mini-batch mode only).
        """
        self.mode = mode
        self.batch_size = batch_size
        self._reset()

    def reset(self) -> None:
        """Reset all queue state without changing mode or batch size."""
        self._reset()

    # ---------------------------------------------------------------------------
    # Mode implementations
    # ---------------------------------------------------------------------------

    def _next_shuffle(self, items: list[QuizItem]) -> QuizItem:
        """No repeats until deck exhausted, then reshuffle."""
        if not self._indices:
            self._indices = list(range(len(items)))
            random.shuffle(self._indices)
        return items[self._indices.pop()]

    def _next_sequential(self, items: list[QuizItem]) -> QuizItem:
        """Return items in order, wrapping back to the start when exhausted."""
        item = items[self._position % len(items)]
        self._position += 1
        return item

    def _next_mini_batch(self, items: list[QuizItem]) -> QuizItem:
        """
        Drill N items at a time before moving to the next batch.

        When the current batch is exhausted, takes the next N items from the
        remaining deck. When the full deck is exhausted, reshuffles and starts
        a new cycle. Items within each batch are shuffled independently.
        """
        if not self._batch_remaining:
            if not self._indices:
                # Full deck exhausted -- reshuffle and start a new cycle.
                self._indices = list(range(len(items)))
                random.shuffle(self._indices)
            batch_size = min(self.batch_size, len(self._indices))
            self._batch_remaining = self._indices[:batch_size]
            self._indices = self._indices[batch_size:]
            random.shuffle(self._batch_remaining)
        return items[self._batch_remaining.pop()]

    def _next_weighted(self, items: list[QuizItem]) -> QuizItem:
        """
        Select items proportionally by weight.

        Items the user misses get higher weights (up to 3x) and appear more
        often. Items answered correctly gradually return to baseline weight.
        Weights are capped at 3.0 to prevent any single item dominating
        the session -- important for large decks like All Reviewed.
        """
        weights = [self._weights.get(item.characters, 1.0) for item in items]
        return random.choices(items, weights=weights)[0]

    def _reset(self) -> None:
        self._indices = []
        self._batch_remaining = []
        self._position = 0
        self._weights = {}


# ---------------------------------------------------------------------------
# Cache and public functions
# ---------------------------------------------------------------------------

# Queue state cached by session_id (UUID generated by the frontend on first load).
_queue_cache: CacheProvider[QuizQueue] = InMemoryCache()


def get_or_create_queue(session_id: str) -> QuizQueue:
    """
    Return the existing queue for a session or create one with default settings.

    Args:
        session_id: The session UUID from the frontend.

    Returns:
        The QuizQueue for this session.
    """
    if not _queue_cache.contains(session_id):
        _queue_cache.set(session_id, QuizQueue())
    return _queue_cache.get(session_id)  # type: ignore[return-value]


def configure_queue(session_id: str, mode: str, batch_size: int) -> None:
    """Configure the queue mode and batch size for a session, resetting state."""
    queue = get_or_create_queue(session_id)
    queue.configure(mode, batch_size)


def reset_queue(session_id: str) -> None:
    """Reset queue state for a session without changing mode or batch size."""
    if _queue_cache.contains(session_id):
        queue = _queue_cache.get(session_id)
        if queue:
            queue.reset()


def record_queue_result(session_id: str, characters: str, correct: bool) -> None:
    """
    Record a guess result for weighted queue adjustment.

    No-op if the session has no queue or the queue is not in weighted mode.

    Args:
        session_id: The session UUID.
        characters: The compound that was shown.
        correct: Whether the guess was correct.
    """
    if _queue_cache.contains(session_id):
        queue = _queue_cache.get(session_id)
        if queue:
            queue.record_result(characters, correct)
